# Generated by Django 3.2 on 2022-08-16 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(max_length=512)),
                ('thumbnail', models.FileField(upload_to='')),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surName', models.CharField(max_length=128, null=True)),
                ('lastName', models.CharField(max_length=128, null=True)),
                ('otherName', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='date of Birth')),
                ('mobile_1', models.CharField(blank=True, max_length=14)),
                ('mobile_2', models.CharField(blank=True, max_length=14)),
                ('email1', models.EmailField(blank=True, max_length=64)),
                ('email2', models.EmailField(blank=True, max_length=64)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.gender')),
                ('maritalStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.maritalstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='type something here', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='type something here', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=128, null=True)),
                ('cost', models.CharField(default='', max_length=128, null=True)),
                ('client', models.CharField(max_length=128, null=True)),
                ('total_floor_area', models.CharField(max_length=128, null=True)),
                ('jobsheet', models.FileField(null=True, upload_to='')),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('completed_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='type something here', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Town_City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.region')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('thumbnail', models.FileField(upload_to='')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='date published')),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_number', models.CharField(default='QW23', max_length=32)),
                ('description', models.TextField(max_length=512)),
                ('dateOfFirstAppointment', models.DateField(blank=True, null=True, verbose_name='date of First Appointment')),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.department')),
                ('office_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.office')),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.person')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.position')),
                ('profession_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profession')),
                ('rank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.rank')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOverview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=256)),
                ('media_content', models.FileField(upload_to='')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.project')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('title_details', models.CharField(max_length=256)),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.sub_categories'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.title'),
        ),
        migrations.AddField(
            model_name='office',
            name='town_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.town_city'),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=512)),
                ('dateOfFirstAppointment', models.DateField(blank=True, null=True, verbose_name='date of First Appointment')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.position')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Board_Of_Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=512)),
                ('dateOfFirstAppointment', models.DateField(blank=True, null=True, verbose_name='date of First Appointment')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.person')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.position')),
            ],
        ),
    ]
