# Generated by Django 3.2 on 2022-08-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board_Of_Director',
            new_name='BoardOfDirectors',
        ),
        migrations.RenameModel(
            old_name='Sub_Categories',
            new_name='SubCategories',
        ),
        migrations.RenameModel(
            old_name='Town_City',
            new_name='TownCity',
        ),
    ]
