# Generated by Django 3.2 on 2023-05-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20230511_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profession',
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.title'),
        ),
    ]
