# Generated by Django 3.2 on 2022-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_categories_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
