# Generated by Django 3.2 on 2023-05-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230512_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='coordinator',
            new_name='project_coordinator',
        ),
    ]
