# Generated by Django 3.2 on 2022-09-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_subcategories_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profession_id',
        ),
        migrations.AddField(
            model_name='person',
            name='profession_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profession'),
        ),
    ]
