# Generated by Django 3.2 on 2022-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rank_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jobsheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
