# Generated by Django 3.2 on 2022-10-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_project_jobsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
