# Generated by Django 3.2 on 2022-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220912_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='office_id',
            new_name='office',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='rank_id',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='projectlead',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
