# Generated by Django 3.2 on 2022-11-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20221024_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created', '-updated', 'name'], 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.RenameField(
            model_name='projectmedia',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectoverview',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projecttag',
            old_name='project_id',
            new_name='project',
        ),
    ]
