# Generated by Django 3.2 on 2022-09-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220912_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlead',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectlead',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
